name: CI

on:
  pull_request:
  # Run when pushing to stable branches
  push:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} (Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            otp: "26.1.2"
            elixir: "1.15.7"
          - os: windows-2022
            otp: "26.1.2"
            elixir: "1.15.7"
          - os: macos-latest
            otp: "26.1.2"
            elixir: "1.15.7"

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install OTP and Elixir
        if: runner.os != 'macOS'
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install OTP and Elixir
        if: runner.os == 'macOS'
        run: |
          brew install elixir
          mix local.hex --force

      - name: Install and compile dependencies
        run: |
          mix deps.get --only test
          mix deps.compile

      - name: Run tests
        run: mix test
